# Generated by Django 3.0.4 on 2020-04-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Add', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='photo',
        ),
    ]
