# Generated by Django 3.0.3 on 2020-02-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0003_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='addedField',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
