# Generated by Django 3.0.3 on 2020-03-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0003_auto_20200311_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpagephotos',
            name='directionsUrl',
        ),
    ]
