# Generated by Django 3.0.3 on 2020-03-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0004_remove_frontpagephotos_directionsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagephotos',
            name='directionsUrl',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
