# Generated by Django 3.0.3 on 2020-02-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0004_testmodel_addedfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='newField',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
