# Generated by Django 3.0.4 on 2020-04-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0005_frontpagephotos_directionsurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmark',
            name='photoIndex',
            field=models.IntegerField(blank=True, max_length=17, null=True),
        ),
    ]
