# Generated by Django 3.0.3 on 2020-02-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0005_testmodel_newfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='newFields',
            field=models.IntegerField(default=4, max_length=10),
            preserve_default=False,
        ),
    ]
