# Generated by Django 3.0.3 on 2020-02-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0007_auto_20200225_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='newFields',
            field=models.IntegerField(max_length=10),
        ),
    ]
