# Generated by Django 3.0.3 on 2020-02-25 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0008_auto_20200225_0223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
