# Generated by Django 3.0.3 on 2020-02-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0009_delete_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
