# Generated by Django 3.0.3 on 2020-02-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0010_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='key',
            field=models.CharField(max_length=10),
        ),
    ]
