# Generated by Django 3.0.3 on 2020-03-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0013_auto_20200302_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
    ]
