# Generated by Django 3.0.3 on 2020-03-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0018_landmark_landmarkphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
    ]
