# Generated by Django 3.0.3 on 2020-03-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0020_landmark_landmarkphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmarkphoto',
            name='id',
        ),
        migrations.AddField(
            model_name='landmarkphoto',
            name='name',
            field=models.CharField(default="Fisherman'sWharf", max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
