# Generated by Django 3.0.3 on 2020-03-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0021_auto_20200302_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
    ]
