# Generated by Django 3.0.3 on 2020-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0023_landmark_landmarkphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
        migrations.AddField(
            model_name='landmarkphoto',
            name='id',
            field=models.AutoField(auto_created=True, default="Fisherman'sWharf", primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landmarkphoto',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
