# Generated by Django 3.0.3 on 2020-03-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0024_auto_20200302_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='landmarkPhoto',
        ),
    ]
