# Generated by Django 3.0.3 on 2020-03-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0027_landmark_landmarkphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
        migrations.DeleteModel(
            name='landmarkPhoto',
        ),
    ]
