# Generated by Django 3.0.3 on 2020-03-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0028_auto_20200302_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='landmarkPhoto',
            fields=[
                ('imgSrc', models.ImageField(default='../static/images/Extras/notFound.jpg', max_length=255, upload_to='')),
                ('longitude', models.FloatField(db_index=True, default='-0.071389', max_length=15)),
                ('latitude', models.FloatField(db_index=True, default='-75.2509766', max_length=15)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='landmark',
            name='landmarkPhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landmarks.landmarkPhoto'),
        ),
    ]
