# Generated by Django 3.0.3 on 2020-03-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0029_auto_20200302_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmark',
            name='landmarkPhoto',
        ),
        migrations.AddField(
            model_name='landmarkphoto',
            name='landmark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Landmarks.landmark'),
        ),
    ]
