# Generated by Django 3.0.3 on 2020-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landmarks', '0032_auto_20200302_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(db_index=True, default='-75.2509766', max_length=15),
        ),
        migrations.AlterField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(db_index=True, default='-0.071389', max_length=15),
        ),
    ]
